[package]
name = "blackhole-transit"
description = "Blackhole transit relay server"

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license = "MIT"

rust-version.workspace = true
edition.workspace = true

[[bin]]
name = "blackhole-transit"
path = "src/main.rs"

[dependencies]
