[package]
name = "blackhole-transit"
description = "Blackhole transit relay server"

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license = "MIT"

rust-version.workspace = true
edition.workspace = true

[[bin]]
name = "blackhole-transit"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros", "io-util", "sync", "time", "signal"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive", "env"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros", "io-util", "sync", "time"] }
