[package]
name = "blackhole-mailbox"
description = "Blackhole rendezvous (mailbox) server"

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

rust-version.workspace = true
edition.workspace = true

[[bin]]
name = "blackhole-mailbox"
path = "src/main.rs"

[dependencies]
